export const UNITS: Unit[] = [
  {
    uuid: "f0b1c9a1-1d84-4c1e-a9d2-5b2d63f9a001",
    title: {
      en: "Unit 1: Basic Expressions",
      zh: "單元 1：基本表達",
      ja: "ユニット1：基本表現",
    },
    description: {
      en: "Very common interjections and simple responses.",
      zh: "常用的感嘆詞與簡單回答。",
      ja: "よく使われる感嘆詞や簡単な返答。",
    },
    vocabulary: ["ああ", "いい", "はい", "いいえ"],
  },
  {
    uuid: "1a2d3e4f-5b6c-7d8e-9f01-23456789abcd",
    title: {
      en: "Unit 2: Pronouns & Demonstratives",
      zh: "單元 2：代名詞與指示詞",
      ja: "ユニット2：代名詞と指示語",
    },
    description: {
      en: "Personal pronouns and basic demonstrative words.",
      zh: "人稱代名詞與基本的指示詞。",
      ja: "人称代名詞と基本的な指示語。",
    },
    vocabulary: [
      "私",
      "私",
      "あなた",
      "あの",
      "あれ",
      "ここ",
      "そこ",
      "あそこ",
      "これ",
      "それ",
      "こっち",
      "そっち",
      "こちら",
      "そちら",
    ],
  },
  {
    uuid: "2b3c4d5e-6f7a-8b9c-0d1e-23456789abcd",
    title: {
      en: "Unit 3: Numbers 1–10",
      zh: "單元 3：數字 1–10",
      ja: "ユニット3：数字1～10",
    },
    description: {
      en: "Basic numbers in kanji, essential for counting.",
      zh: "基本的數字，用於計數。",
      ja: "基本的な数字で、数えるために必須。",
    },
    vocabulary: [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "七",
      "八",
      "九",
      "九",
      "十",
      "十",
      "零",
    ],
  },
  {
    uuid: "3c4d5e6f-7a8b-9c0d-1e2f-3456789abcde",
    title: {
      en: "Unit 4: Native Counters",
      zh: "單元 4：和語數詞",
      ja: "ユニット4：和語の数詞",
    },
    description: {
      en: "Native Japanese counting system used for objects.",
      zh: "日語固有的數詞，用來數物品。",
      ja: "日本語固有の数え方で、物を数えるときに使う。",
    },
    vocabulary: [
      "一つ",
      "二つ",
      "三つ",
      "四つ",
      "五つ",
      "六つ",
      "七つ",
      "八つ",
      "九つ",
    ],
  },
  {
    uuid: "4d5e6f7a-8b9c-0d1e-2f3a-456789abcdef",
    title: {
      en: "Unit 5: Days of the Month",
      zh: "單元 5：日期的表達",
      ja: "ユニット5：日付の表現",
    },
    description: {
      en: "Special counters used for calendar days.",
      zh: "用於表示日曆日期的特別數詞。",
      ja: "カレンダーの日付を表す特別な数え方。",
    },
    vocabulary: [
      "十日",
      "五日",
      "七日",
      "九日",
      "一日",
      "一日",
      "二日",
      "三日",
      "四日",
      "六日",
      "八日",
    ],
  },
  {
    uuid: "5e6f7a8b-9c0d-1e2f-3a4b-56789abcdef0",
    title: {
      en: "Unit 6: Time Words",
      zh: "單元 6：時間詞彙",
      ja: "ユニット6：時間の言葉",
    },
    description: {
      en: "Words for days, months, and temporal expressions.",
      zh: "與日期、月份與時間相關的詞彙。",
      ja: "日付・月・時間に関する言葉。",
    },
    vocabulary: [
      "一月",
      "今日",
      "昨日",
      "明日",
      "一昨日",
      "明後日",
      "今",
      "今朝",
      "今晩",
      "今年",
      "来年",
      "去年",
      "先月",
      "来月",
      "先週",
      "来週",
    ],
  },
  {
    uuid: "6f7a8b9c-0d1e-2f3a-4b5c-6789abcdef01",
    title: {
      en: "Unit 7: People & Family",
      zh: "單元 7：人物與家庭",
      ja: "ユニット7：人と家族",
    },
    description: {
      en: "Family members, relatives, and friends.",
      zh: "家庭成員、親戚與朋友。",
      ja: "家族、親戚、友達。",
    },
    vocabulary: [
      "家",
      "学校",
      "学生",
      "先生",
      "生徒",
      "子供",
      "男",
      "女",
      "兄",
      "姉",
      "弟",
      "妹",
      "お兄さん",
      "お姉さん",
      "お父さん",
      "お母さん",
      "おじいさん",
      "おばあさん",
      "両親",
      "兄弟",
      "友達",
      "家族",
      "父",
      "母",
    ],
  },
  {
    uuid: "7a8b9c0d-1e2f-3a4b-5c6d-789abcdef012",
    title: {
      en: "Unit 8: Animals & Food Items",
      zh: "單元 8：動物與食物",
      ja: "ユニット8：動物と食べ物",
    },
    description: {
      en: "Common animals and basic food vocabulary.",
      zh: "常見動物與基本食物詞彙。",
      ja: "一般的な動物と基本的な食べ物の語彙。",
    },
    vocabulary: [
      "犬",
      "猫",
      "鳥",
      "魚",
      "肉",
      "野菜",
      "果物",
      "卵",
      "牛乳",
      "パン",
      "お茶",
      "水",
      "牛肉",
      "鶏肉",
      "砂糖",
      "醤油",
      "バター",
      "カレー",
      "紅茶",
      "コーヒー",
    ],
  },
  {
    uuid: "8b9c0d1e-2f3a-4b5c-6d7e-89abcdef0123",
    title: {
      en: "Unit 9: Daily Time Expressions",
      zh: "單元 9：每日時間表達",
      ja: "ユニット9：日常の時間表現",
    },
    description: {
      en: "Times of day and meal-related words.",
      zh: "一天中的時間及用餐相關詞彙。",
      ja: "一日の時間と食事に関連する言葉。",
    },
    vocabulary: ["朝", "昼", "晩", "夕方", "夜"],
  },
  {
    uuid: "9c0d1e2f-3a4b-5c6d-7e8f-9abcdef01234",
    title: {
      en: "Unit 10: Seasons & Weather",
      zh: "單元 10：季節與天氣",
      ja: "ユニット10：季節と天気",
    },
    description: {
      en: "Words for seasons and common weather expressions.",
      zh: "季節與常見天氣表達詞彙。",
      ja: "季節と一般的な天気の表現。",
    },
    vocabulary: [
      "春",
      "夏",
      "秋",
      "冬",
      "天気",
      "雨",
      "雪",
      "曇り",
      "晴れ",
      "暑い",
      "寒い",
      "暖かい",
      "涼しい",
      "熱い",
      "冷たい",
    ],
  },
  {
    uuid: "0d1e2f3a-4b5c-6d7e-8f90-abcdef012345",
    title: {
      en: "Unit 11: Basic Verbs 1",
      zh: "單元 11：基本動詞 1",
      ja: "ユニット11：基本動詞 1",
    },
    description: {
      en: "Common everyday verbs for movement and basic actions.",
      zh: "日常生活中常用的動作動詞。",
      ja: "日常生活でよく使う動作動詞。",
    },
    vocabulary: [
      "行く",
      "来る",
      "帰る",
      "食べる",
      "飲む",
      "見る",
      "聞く",
      "話す",
      "する",
      "寝る",
      "起きる",
      "使う",
      "作る",
      "書く",
      "読む",
      "待つ",
      "座る",
      "立つ",
      "歩く",
      "泳ぐ",
      "走る",
      "登る",
      "降りる",
    ],
  },
  {
    uuid: "1e2f3a4b-5c6d-7e8f-90ab-cdef01234567",
    title: {
      en: "Unit 12: Basic Verbs 2",
      zh: "單元 12：基本動詞 2",
      ja: "ユニット12：基本動詞 2",
    },
    description: {
      en: "More verbs for daily life and object manipulation.",
      zh: "更多日常生活與操作物品的動詞。",
      ja: "日常生活や物の操作に使う動詞。",
    },
    vocabulary: [
      "出る",
      "入る",
      "入れる",
      "出す",
      "置く",
      "閉める",
      "閉まる",
      "渡す",
      "返す",
      "開く",
    ],
  },
  {
    uuid: "2f3a4b5c-6d7e-8f90-ab12-def012345678",
    title: {
      en: "Unit 13: Directions & Positions",
      zh: "單元 13：方位與位置",
      ja: "ユニット13：方向と位置",
    },
    description: {
      en: "Words for directions, positions, and relative locations.",
      zh: "表示方位、位置與相對位置的詞彙。",
      ja: "方向や位置、相対的な場所を表す言葉。",
    },
    vocabulary: [
      "上",
      "下",
      "左",
      "右",
      "前",
      "後",
      "後ろ",
      "中",
      "外",
      "外",
      "近く",
      "遠い",
    ],
  },
  {
    uuid: "3a4b5c6d-7e8f-90ab-12cd-ef0123456789",
    title: {
      en: "Unit 14: Sizes & Measurements",
      zh: "單元 14：大小與測量",
      ja: "ユニット14：大きさと測定",
    },
    description: {
      en: "Words describing size, height, and dimensions.",
      zh: "描述大小、高矮與長短的詞彙。",
      ja: "大きさ、高さ、寸法を表す言葉。",
    },
    vocabulary: [
      "高い",
      "低い",
      "大きい",
      "小さい",
      "長い",
      "短い",
      "新しい",
      "古い",
      "悪い",
      "早い",
      "遅い",
      "強い",
      "弱い",
      "重い",
      "軽い",
    ],
  },
  {
    uuid: "4b5c6d7e-8f90-ab12-3cde-f0123456789a",
    title: {
      en: "Unit 15: Colors & Appearance",
      zh: "單元 15：顏色與外觀",
      ja: "ユニット15：色と見た目",
    },
    description: {
      en: "Color adjectives and basic appearance words.",
      zh: "顏色形容詞與基本外觀詞彙。",
      ja: "色の形容詞と基本的な見た目の言葉。",
    },
    vocabulary: [
      "赤",
      "青",
      "黄色",
      "白",
      "黒",
      "赤い",
      "青い",
      "黄色い",
      "白い",
      "黒い",
      "色",
    ],
  },
  {
    uuid: "5c6d7e8f-90ab-12cd-34ef-0123456789ab",
    title: {
      en: "Unit 16: Body Parts",
      zh: "單元 16：身體部位",
      ja: "ユニット16：体の部位",
    },
    description: {
      en: "Words for body parts and features.",
      zh: "身體部位及五官相關詞彙。",
      ja: "体の部位や顔の特徴を表す言葉。",
    },
    vocabulary: [
      "顔",
      "頭",
      "手",
      "足",
      "口",
      "目",
      "耳",
      "鼻",
      "背",
      "体",
      "お腹",
    ],
  },
  {
    uuid: "6d7e8f90-ab12-3cde-45f0-123456789abc",
    title: {
      en: "Unit 17: Places & Buildings",
      zh: "單元 17：地點與建築物",
      ja: "ユニット17：場所と建物",
    },
    description: {
      en: "Common locations, buildings, and public places.",
      zh: "常見地點、建築與公共場所。",
      ja: "一般的な場所、建物、公共施設。",
    },
    vocabulary: [
      "店",
      "駅",
      "会社",
      "教室",
      "図書館",
      "公園",
      "病院",
      "郵便局",
      "銀行",
      "デパート",
      "映画館",
      "喫茶店",
      "ホテル",
    ],
  },
  {
    uuid: "7e8f90ab-12cd-34ef-56f0-23456789abcd",
    title: {
      en: "Unit 18: Transportation & Tools",
      zh: "單元 18：交通工具與工具",
      ja: "ユニット18：交通手段と道具",
    },
    description: {
      en: "Transportation modes and common everyday tools.",
      zh: "交通工具與常用日常物品。",
      ja: "交通手段と日常の道具。",
    },
    vocabulary: [
      "時計",
      "電車",
      "自転車",
      "自動車",
      "車",
      "飛行機",
      "道",
      "町",
      "山",
      "海",
      "庭",
      "橋",
      "門",
    ],
  },
  {
    uuid: "8f90ab12-3cde-45f0-67f1-3456789abcde",
    title: {
      en: "Unit 19: Media & Literature",
      zh: "單元 19：媒體與文學",
      ja: "ユニット19：メディアと文学",
    },
    description: {
      en: "Books, magazines, music, films, and writing.",
      zh: "書籍、雜誌、音樂、電影與寫作。",
      ja: "本、雑誌、音楽、映画、文章。",
    },
    vocabulary: [
      "本",
      "新聞",
      "雑誌",
      "手紙",
      "写真",
      "映画",
      "音楽",
      "絵",
      "歌",
      "作文",
      "文章",
      "言葉",
      "意味",
      "漢字",
      "平仮名",
      "片仮名",
    ],
  },
  {
    uuid: "90ab12cd-34ef-56f0-78a1-456789abcdef",
    title: {
      en: "Unit 20: Study & Learning",
      zh: "單元 20：學習與課業",
      ja: "ユニット20：勉強と学習",
    },
    description: {
      en: "Vocabulary for learning, studying, and school activities.",
      zh: "學習、讀書與課業相關詞彙。",
      ja: "勉強や学習、学校の活動に関する言葉。",
    },
    vocabulary: [
      "勉強",
      "宿題",
      "授業",
      "練習",
      "習う",
      "覚える",
      "教える",
      "答える",
      "質問",
      "知る",
      "分かる",
      "できる",
      "忘れる",
    ],
  },
  {
    uuid: "a1b2c3d4-5e6f-7a8b-9c0d-1e2f34567890",
    title: {
      en: "Unit 21: Actions & Transactions",
      zh: "單元 21：行為與交易",
      ja: "ユニット21：行動と取引",
    },
    description: {
      en: "Verbs related to buying, selling, borrowing, lending, and basic actions.",
      zh: "與買、賣、借、貸及基本行為相關的動詞。",
      ja: "買う、売る、借りる、貸すなどの基本動作の動詞。",
    },
    vocabulary: [
      "買う",
      "売る",
      "借りる",
      "貸す",
      "押す",
      "掛ける",
      "開ける",
      "出かける",
    ],
  },
  {
    uuid: "b2c3d4e5-6f7a-8b9c-0d1e-2f3456789012",
    title: {
      en: "Unit 22: Food & Utensils",
      zh: "單元 22：食物與餐具",
      ja: "ユニット22：食べ物と食器",
    },
    description: {
      en: "Words for snacks, meals, dishes, and utensils.",
      zh: "零食、餐點、盤子及餐具的詞彙。",
      ja: "お菓子、食事、皿、調理器具の言葉。",
    },
    vocabulary: [
      "お菓子",
      "お酒",
      "お弁当",
      "お皿",
      "お手洗い",
      "アパート",
      "コップ",
      "コート",
      "スカート",
      "ズボン",
      "シャツ",
      "セーター",
      "ワイシャツ",
      "帽子",
      "靴",
      "靴下",
      "かばん",
      "カメラ",
      "ノート",
      "ペン",
      "鉛筆",
      "テーブル",
      "椅子",
      "机",
      "ベッド",
      "テレビ",
      "ラジオ",
      "テープレコーダー",
      "フィルム",
      "ストーブ",
      "フォーク",
      "スプーン",
      "ナイフ",
    ],
  },
  {
    uuid: "c3d4e5f6-7a8b-9c0d-1e2f-345678901234",
    title: {
      en: "Unit 23: Cooking & Restaurants",
      zh: "單元 23：料理與餐廳",
      ja: "ユニット23：料理とレストラン",
    },
    description: {
      en: "Vocabulary for cooking, restaurants, and food-related activities.",
      zh: "料理、餐廳與食物相關活動的詞彙。",
      ja: "料理、レストラン、食べ物に関する言葉。",
    },
    vocabulary: ["料理", "旅行", "廊下", "冷蔵庫", "レストラン", "レコード"],
  },
  {
    uuid: "d4e5f6a7-8b9c-0d1e-2f3a-456789012345",
    title: {
      en: "Unit 24: Describing People & Qualities",
      zh: "單元 24：描述人物與特質",
      ja: "ユニット24：人と特性の表現",
    },
    description: {
      en: "Adjectives and verbs describing people’s age, appearance, and actions.",
      zh: "描述人物年齡、外觀與行為的形容詞與動詞。",
      ja: "人の年齢、外見、行動を表す形容詞と動詞。",
    },
    vocabulary: [
      "若い",
      "渡る",
      "明るい",
      "上げる",
      "朝御飯",
      "遊ぶ",
      "厚い",
      "浴びる",
      "危ない",
      "甘い",
      "余り",
      "飴",
      "洗う",
      "在る",
      "有る",
      "言う",
      "いかが",
      "いくつ",
      "いくら",
      "池",
    ],
  },
  {
    uuid: "e5f6a7b8-9c0d-1e2f-3a4b-567890123456",
    title: {
      en: "Unit 25: People & Professions",
      zh: "單元 25：人物與職業",
      ja: "ユニット25：人と職業",
    },
    description: {
      en: "Words for people, professions, and common characteristics.",
      zh: "人物、職業及常見特徵的詞彙。",
      ja: "人、職業、一般的な特徴を表す言葉。",
    },
    vocabulary: [
      "医者",
      "忙しい",
      "痛い",
      "一番",
      "いつ",
      "一緒",
      "いつも",
      "嫌",
      "入口",
      "居る",
      "要る",
      "色々",
      "薄い",
      "歌う",
      "うち",
      "生まれる",
      "うるさい",
      "上着",
      "英語",
      "エレベーター",
      "～円",
    ],
  },
  {
    uuid: "f6a7b8c9-0d1e-2f3a-4b5c-678901234567",
    title: {
      en: "Unit 26: Politeness & Taste",
      zh: "單元 26：禮貌與味覺",
      ja: "ユニット26：丁寧さと味",
    },
    description: {
      en: "Words for politeness, taste, quantity, and daily interactions.",
      zh: "禮貌、味道、數量與日常互動相關詞彙。",
      ja: "礼儀、味、量、日常のやり取りに関する言葉。",
    },
    vocabulary: [
      "お～",
      "美味しい",
      "多い",
      "大きな",
      "大勢",
      "お金",
      "奥さん",
      "伯父; 叔父さん",
      "男の子",
      "おととし",
      "大人",
      "同じ",
      "伯母さん; 叔母さん",
      "お風呂",
      "おまわりさん",
      "面白い",
      "終る",
      "女の子",
      "～回",
      "～階",
      "外国",
      "外国人",
      "階段",
    ],
  },
  {
    uuid: "07b8c9d0-1e2f-3a4b-5c6d-789012345678",
    title: {
      en: "Unit 27: Shopping & Numbers",
      zh: "單元 27：購物與數字",
      ja: "ユニット27：買い物と数字",
    },
    description: {
      en: "Numbers, shopping-related words, and counters.",
      zh: "數字、購物相關詞彙與量詞。",
      ja: "数字、買い物に関する言葉、助数詞。",
    },
    vocabulary: [
      "買い物",
      "かかる",
      "鍵",
      "～か月",
      "かける",
      "傘",
      "風",
      "風邪",
      "方",
      "～月",
      "カップ",
      "家庭",
      "角",
      "花瓶",
      "かぶる",
      "紙",
      "火曜日",
      "辛い",
      "～がる",
      "カレンダー",
      "川; 河",
      "～側",
      "可愛い",
    ],
  },
  {
    uuid: "18c9d0e1-2f3a-4b5c-6d7e-890123456789",
    title: {
      en: "Unit 28: Daily Life & Objects",
      zh: "單元 28：日常生活與物品",
      ja: "ユニット28：日常生活と物",
    },
    description: {
      en: "Daily life words, objects, and basic needs.",
      zh: "日常生活詞彙、物品與基本需求。",
      ja: "日常生活に関する言葉、物、基本的な必要品。",
    },
    vocabulary: [
      "木",
      "消える",
      "北",
      "ギター",
      "汚い",
      "切手",
      "切符",
      "嫌い",
      "切る",
      "着る",
      "綺麗",
      "キロ; キログラム",
      "キロ; キロメートル",
      "金曜日",
      "薬",
      "下さい",
      "国",
      "曇る",
      "暗い",
      "～くらい; ぐらい",
      "クラス",
      "グラム",
      "警官",
      "消す",
      "結構",
    ],
  },
  {
    uuid: "29d0e1f2-3a4b-5c6d-7e8f-90123456789a",
    title: {
      en: "Unit 29: Family & Time",
      zh: "單元 29：家庭與時間",
      ja: "ユニット29：家族と時間",
    },
    description: {
      en: "Family, numbers, days, and time expressions.",
      zh: "家庭成員、數字、日期與時間表達。",
      ja: "家族、数字、日付や時間の表現。",
    },
    vocabulary: [
      "結婚",
      "月曜日",
      "玄関",
      "元気",
      "～個",
      "～語",
      "交差点",
      "交番",
      "声",
      "午後",
      "午前",
      "この",
      "御飯",
      "コピーする",
      "困る",
      "～ころ; ～ごろ",
      "今月",
      "今週",
      "こんな",
      "～歳",
    ],
  },
  {
    uuid: "3ae1f2b3-4c5d-6e7f-8a90-0123456789ab",
    title: {
      en: "Unit 30: Daily Actions & Politeness",
      zh: "單元 30：日常行為與禮貌",
      ja: "ユニット30：日常の行動と礼儀",
    },
    description: {
      en: "Daily actions, greetings, and polite expressions.",
      zh: "日常行為、問候與禮貌表達。",
      ja: "日常の行動、挨拶、丁寧な表現。",
    },
    vocabulary: [
      "財布",
      "先",
      "咲く",
      "差す",
      "～冊",
      "さ来年",
      "～さん",
      "散歩",
      "～時",
      "～時",
      "塩",
      "しかし",
      "時間",
      "～時間",
      "仕事",
      "辞書",
      "静か",
      "死ぬ",
      "字引",
      "自分",
      "締める",
      "じゃ; じゃあ",
      "シャワー",
      "～中",
      "～中",
      "～週間",
    ],
  },
  {
    uuid: "4bf2c3d4-5e6f-7a8b-9c0d-1234567890ab",
    title: {
      en: "Unit 31: Skills & Abilities",
      zh: "單元 31：技能與能力",
      ja: "ユニット31：スキルと能力",
    },
    description: {
      en: "Words for ability, skill, and doing things well or poorly.",
      zh: "表示能力、技巧及做事情的好壞。",
      ja: "能力、スキル、物事の上手・下手を表す言葉。",
    },
    vocabulary: [
      "上手",
      "丈夫",
      "食堂",
      "～人",
      "～人",
      "水曜日",
      "吸う",
      "好き",
      "～すぎ",
      "少ない",
      "すぐに",
      "少し",
      "～ずつ",
      "スポーツ",
      "住む",
      "石鹸",
      "背広",
      "狭い",
      "ゼロ",
      "千",
      "洗濯",
      "全部",
      "そう; そうです",
      "掃除",
      "そうして; そして",
    ],
  },
  {
    uuid: "5cf3d4e5-6f7a-8b9c-0d1e-234567890abc",
    title: {
      en: "Unit 32: Connecting & Indicating",
      zh: "單元 32：連接與指示",
      ja: "ユニット32：接続と指示",
    },
    description: {
      en: "Words used to connect thoughts and indicate objects or places.",
      zh: "用來連接語意及指示物品或地點的詞彙。",
      ja: "考えをつなげたり、物や場所を指示したりする言葉。",
    },
    vocabulary: [
      "その",
      "そば",
      "空",
      "それから",
      "それでは",
      "～台",
      "大学",
      "大使館",
      "大丈夫",
      "大好き",
      "大切",
      "台所",
      "大変",
      "～だけ",
      "沢山",
      "タクシー",
      "～たち",
      "たて",
      "建物",
      "楽しい",
      "頼む",
      "たばこ",
      "多分",
      "食べ物",
      "誰",
      "誰か",
      "誕生日",
      "段々",
      "小さな",
      "近い",
      "違う",
    ],
  },
  {
    uuid: "6df4e5f6-7a8b-9c0d-1e2f-34567890abcd",
    title: {
      en: "Unit 33: Travel & Directions",
      zh: "單元 33：旅行與方向",
      ja: "ユニット33：旅行と方向",
    },
    description: {
      en: "Words for travel, streets, and directions.",
      zh: "旅遊、街道與方向相關詞彙。",
      ja: "旅行、通り、方向に関する言葉。",
    },
    vocabulary: [
      "地下鉄",
      "地図",
      "茶色",
      "茶碗",
      "丁度",
      "ちょっと",
      "疲れる",
      "次",
      "着く",
      "つける",
      "勤める",
      "つまらない",
      "テープ",
      "出口",
      "テスト",
      "では",
      "でも",
      "電気",
      "電話",
      "戸",
    ],
  },
  {
    uuid: "7ef5f6a7-8b9c-0d1e-2f3a-4567890abcde",
    title: {
      en: "Unit 34: Places & Questions",
      zh: "單元 34：地點與疑問",
      ja: "ユニット34：場所と疑問",
    },
    description: {
      en: "Places, basic question words, and expressions of location.",
      zh: "地點、基本疑問詞與位置表達。",
      ja: "場所、基本的な疑問詞、場所の表現。",
    },
    vocabulary: [
      "～度",
      "ドア",
      "トイレ",
      "どう",
      "どうして",
      "どうぞ",
      "動物",
      "どうも",
      "時々",
      "どこ",
      "所",
      "年",
      "どちら",
      "どっち",
      "とても",
      "どなた",
      "隣",
      "どの",
      "飛ぶ",
      "止まる",
      "土曜日",
      "取る",
      "撮る",
      "どれ",
      "どんな",
    ],
  },
  {
    uuid: "8f06a7b8-9c0d-1e2f-3a4b-567890abcdef",
    title: {
      en: "Unit 35: Negation & Loss",
      zh: "單元 35：否定與喪失",
      ja: "ユニット35：否定と喪失",
    },
    description: {
      en: "Words for negation, loss, and absence.",
      zh: "表示否定、喪失與不存在的詞彙。",
      ja: "否定、喪失、不在を表す言葉。",
    },
    vocabulary: [
      "ない",
      "鳴く",
      "無くす",
      "なぜ",
      "夏休み",
      "～など",
      "何",
      "名前",
      "並ぶ",
      "並べる",
      "なる",
      "何～",
      "にぎやか",
      "西",
      "～日",
      "日曜日",
      "荷物",
      "ニュース",
      "脱ぐ",
      "温い",
    ],
  },
  {
    uuid: "9f17b8c9-0d1e-2f3a-4b5c-67890abcdef1",
    title: {
      en: "Unit 36: Clothing & Drinks",
      zh: "單元 36：服裝與飲料",
      ja: "ユニット36：服と飲み物",
    },
    description: {
      en: "Clothing, accessories, and drinks vocabulary.",
      zh: "服裝、配件與飲料詞彙。",
      ja: "服、アクセサリー、飲み物に関する言葉。",
    },
    vocabulary: [
      "ネクタイ",
      "～年",
      "飲み物",
      "乗る",
      "歯",
      "パーティー",
      "～杯",
      "灰皿",
      "葉書",
      "はく",
      "箱",
      "箸",
      "始まる",
      "初め; 始め",
      "初めて",
      "バス",
      "二十歳",
      "働く",
      "二十日",
      "花",
      "話",
      "速い",
      "貼る",
      "晴れる",
    ],
  },
  {
    uuid: "af28c9d0-1e2f-3a4b-5c6d-7890abcdef12",
    title: {
      en: "Unit 37: Time Expressions",
      zh: "單元 37：時間表達",
      ja: "ユニット37：時間の表現",
    },
    description: {
      en: "Hours, parts of the day, and daily routines.",
      zh: "小時、一天的時間段與日常作息。",
      ja: "時間、1日の時間帯、日常のルーティン。",
    },
    vocabulary: [
      "半",
      "～番",
      "ハンカチ",
      "番号",
      "晩御飯",
      "半分",
      "東",
      "～匹",
      "引く",
      "弾く",
      "人",
      "一人",
      "暇",
      "百",
      "病気",
      "昼御飯",
      "広い",
      "封筒",
      "プール",
      "吹く",
    ],
  },
  {
    uuid: "bf39d0e1-2f3a-4b5c-6d7e-890abcdef123",
    title: {
      en: "Unit 38: Clothing & Pets",
      zh: "單元 38：衣物與寵物",
      ja: "ユニット38：服とペット",
    },
    description: {
      en: "Clothes, pets, and descriptive adjectives.",
      zh: "服裝、寵物及形容詞詞彙。",
      ja: "服、ペット、形容詞。",
    },
    vocabulary: [
      "服",
      "豚肉",
      "二人",
      "太い",
      "降る",
      "～分",
      "ページ",
      "下手",
      "ペット",
      "部屋",
      "辺",
      "便利",
      "ボールペン",
      "ポケット",
      "欲しい",
      "ポスト",
      "細い",
      "ボタン",
      "～本",
      "本棚",
      "本当",
      "～枚",
      "毎朝",
      "毎月",
    ],
  },
  {
    uuid: "cf4ae1f2-3a4b-5c6d-7e8f-90123456789b",
    title: {
      en: "Unit 39: Daily Frequency",
      zh: "單元 39：日常頻率",
      ja: "ユニット39：日常の頻度",
    },
    description: {
      en: "Words expressing daily, weekly, monthly, or yearly frequency.",
      zh: "表達每日、每週、每月或每年頻率的詞彙。",
      ja: "毎日、毎週、毎月、毎年の頻度を表す言葉。",
    },
    vocabulary: [
      "毎週",
      "毎日",
      "毎年",
      "毎晩",
      "～前",
      "曲る",
      "まずい",
      "また",
      "まだ",
      "まっすぐ",
      "マッチ",
      "窓",
      "丸い; 円い",
      "万",
      "万年筆",
      "磨く",
      "見せる",
      "緑",
      "皆さん",
      "南",
      "みんな",
      "向こう",
      "難しい",
      "村",
      "メートル",
      "眼鏡",
    ],
  },
  {
    uuid: "df5bf203-4c5d-6e7f-8a90-0123456789bc",
    title: {
      en: "Unit 40: Communication & Objects",
      zh: "單元 40：交流與物品",
      ja: "ユニット40：コミュニケーションと物",
    },
    description: {
      en: "Words for communication, objects, and social interactions.",
      zh: "交流、物品與社交互動詞彙。",
      ja: "コミュニケーション、物、社会的なやり取りの言葉。",
    },
    vocabulary: [
      "もう",
      "木曜日",
      "もしもし",
      "持つ",
      "もっと",
      "物",
      "問題",
      "～屋",
      "八百屋",
      "易しい",
      "安い",
      "休み",
      "休む",
      "やる",
      "夕飯",
      "昨夜",
      "有名",
      "ゆっくりと",
      "洋服",
      "よく",
      "横",
      "呼ぶ",
      "ラジオカセ",
      "りっぱ",
      "留学生",
      "会う",
    ],
  },
];

export type Unit = {
  uuid: string;
  title: {
    en: string;
    zh: string;
    ja: string;
  };
  description: {
    en: string;
    zh: string;
    ja: string;
  };
  vocabulary: string[];
};
